### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by Eenae** [unitprotocol/wrapped-assets#1]
* https://github.com/unitprotocol/wrapped-assets/blob/2723ad8f3e5d6baad35f5177c12d5f94f6c541ae/contracts/WrappedAsset.sol#L22-L30
Will work incorrectly if actual transferred value differs from requested (e.g. fees, etc).

* https://github.com/unitprotocol/wrapped-assets/blob/2723ad8f3e5d6baad35f5177c12d5f94f6c541ae/contracts/WrappedAsset.sol#L41
Not sure if a space in `symbol` is a good idea. Some third-party soft will definitely puke )

Moreover, is it worth to push these into ERC20 ctor https://github.com/unitprotocol/wrapped-assets/blob/2723ad8f3e5d6baad35f5177c12d5f94f6c541ae/contracts/WrappedAsset.sol#L36-L42 ?

And also store `ERC20(underlying).decimals()` locally?

**Comment by 34x4p08** [comment]
> is it worth to push these into ERC20 ctor?

No, since there are tokens that will fail at creation, e. g. MKR.
